config/routes.rb
Rails.application.routes.draw do
  root to: "plants#index"

  devise_for :users

  resources :plants do
    resources :favourites, only: [:index]
    resources :plant_interests, only: [:create]

    member do
      get :chats, to: "plant_chats#index"
    end
  end

  resources :favourites, only: [:index, :destroy]
  resources :my_plants, only: [:index]
  resources :categories, only: [:show]

  resources :chats, only: [:show, :index] do
    resources :messages, only: [:create] # I'm too lazy to replace simple form on chats#show, so I'm leaving this here to avoid the error
  end

  resources :demo_actions, only: [:index] do
    collection do
      get :steph_response
      get :alex_proposal
    end
  end
end

app/controllers/my_plants_controller.rb
class MyPlantsController < ApplicationController
  def index
    @plants = policy_scope(Plant).where(user: current_user)
  end
end

app/views/my_plants/index.html.erb
<h1 class="my-plants__title font-text font-weight-medium font-size-24 font-colour-charcoal">Your Plants</h1>

<% @plants.each do |plant| %>
  <div class="my-plant-card">
    <%= link_to plant_path(plant) do %>
      <div class="my-plant-card__picture" style="background-image: url('<%= cl_image_path plant.cover_photo.key %>');"></div>
    <% end %>
    <div class="my-plant-card__middle">
      <p class="my-plant-card__title font-text font-size-16 font-colour-charcoal"><%= plant.title %></p>
      <%= link_to "#{pluralize(plant.plant_interests.count, "person")} interested", chats_plant_path(plant), class: "font-text font-size-16 font-colour-light-grey" %>
    </div>
    <div class="my-plant-card__end">
      <p class="font-text font-size-14 font-colour-light-grey">Added on <%= plant.created_at.strftime("%b %e, %Y") %></p>
      <div>
        <%= link_to "Edit details", edit_plant_path(plant), class: "font-text font-size-14 font-weight-medium font-colour-black" %>
        <%= link_to "Delete", plant_path(plant), method: :delete, class: "my-plant-card__delete font-text font-size-14 font-weight-medium font-colour-red" %>
      </div>
    </div>
  </div>
<% end %>