config/routes.rb
Rails.application.routes.draw do
  root to: "plants#index"

  devise_for :users

  resources :plants do
    resources :favourites, only: [:index]
    resources :plant_interests, only: [:create]

    member do
      get :chats, to: "plant_chats#index"
    end
  end

  resources :favourites, only: [:index, :destroy]
  resources :my_plants, only: [:index]
  resources :categories, only: [:show]

  resources :chats, only: [:show, :index] do
    resources :messages, only: [:create] # I'm too lazy to replace simple form on chats#show, so I'm leaving this here to avoid the error
  end

  resources :demo_actions, only: [:index] do
    collection do
      get :steph_response
      get :alex_proposal
    end
  end
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :plant

  validates :user, uniqueness: { scope: :plant }

  validate :validate_plant_not_owned_by_user

  def self.already_existing_between(user, plant)
    Favourite.find_by(user: user, plant: plant)
  end

  private

  def validate_plant_not_owned_by_user
    if plant.user == user
      errors.add(:plant, "owned by user")
    end
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    authorize(Favourite)
    @favourites = policy_scope(Favourite).includes(:plant)
  end

  def destroy
    favourite = Favourite.find(params[:id])

    authorize(favourite)
    favourite.destroy

    redirect_to favourites_path
  end
end

app/views/favourites/index.html.erb
<h1 class="favourites__title font-text font-weight-medium font-size-24 font-colour-charcoal">Your Favourites</h1>

<div class="favourites-container">
  <% @favourites.each do |favourite| %>
    <div class="favourite-card">
      <%= link_to plant_path(favourite.plant) do %>
        <div class="favourite-card__picture" style="background-image: url('<%= cl_image_path favourite.plant.cover_photo.key %>');"></div>
      <% end %>
      <div class="favourite-card__middle">
        <%= link_to plant_path(favourite.plant) do %>
          <p class="font-text font-size-16 font-colour-charcoal"><%= favourite.plant.title %></p>
        <% end %>
      </div>
      <div class="favourite-card__end">
        <p class="font-text font-size-14 font-colour-light-grey">Favourited on <%= favourite.created_at.strftime("%b %e, %Y") %></p>
        <%= link_to "Unfavourite", favourite_path(favourite), remote: true, method: :delete, class: "font-text font-size-14 font-weight-medium font-colour-black" %>
      </div>
    </div>
  <% end %>
</div>