config/routes.rb
Rails.application.routes.draw do
  root to: "plants#index"

  devise_for :users

  resources :plants do
    resources :favourites, only: [:index]
    resources :plant_interests, only: [:create]

    member do
      get :chats, to: "plant_chats#index"
    end
  end

  resources :favourites, only: [:index, :destroy]
  resources :my_plants, only: [:index]
  resources :categories, only: [:show]

  resources :chats, only: [:show, :index] do
    resources :messages, only: [:create] # I'm too lazy to replace simple form on chats#show, so I'm leaving this here to avoid the error
  end

  resources :demo_actions, only: [:index] do
    collection do
      get :steph_response
      get :alex_proposal
    end
  end
end

app/models/plant.rb
require "open-uri"

class Plant < ApplicationRecord
  belongs_to :user
  has_many :plant_categories, dependent: :destroy
  has_many :categories, through: :plant_categories
  has_many :plant_interests, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :ratings, dependent: :destroy

  has_many_attached :pictures
  has_one_attached :cover_photo

  validates :title, presence: true, length: { maximum: 80 }
  validates :description, length: { maximum: 2000 }

  validate :validate_has_cover_photo
  validate :validate_has_no_more_than_four_pictures

  include PgSearch::Model
  pg_search_scope(:search_by_title_and_description,
  against: [ :title, :description ],
  using: {
    tsearch: { prefix: true }
  }
  )
  
  def public
    !private
  end
  
  def price=(price_in_dollars)
    self.price_cents = price_in_dollars.to_i * 100
  end
  
  def price
    price_cents / 100
  end
  
  def validate_has_cover_photo
    if !cover_photo.attached?
      errors.add(:cover_photo, "can't be blank")
    end
  end
  
  def validate_has_no_more_than_four_pictures
    if pictures.length > 4
      errors.add(:pictures, "maximum of four")
    end
  end

  # Cloudinary, when requested for a never-before-requested transformed image, takes some time to make the transformation

  # private

  # include CloudinaryHelper
  # after_commit :pre_generate_cloudinary_crops

  # def pre_generate_cloudinary_crops
  #   if cover_photo.attached?
  #     URI.open(cl_image_path(cover_photo.key, height: 380, crop: :scale))
  #   end

  #   if pictures.attached?
  #     pictures.each { |pic| URI.open(cl_image_path(pic.key, height: 380, crop: :scale)) }
  #   end
  # end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    authorize(Plant)

    @plants = policy_scope(Plant)
      .order("user_id = #{current_user&.id || 0}")
      .includes([
        { user: { profile_picture_attachment: :blob }},
        { favourites: :user }
      ])
      .with_attached_cover_photo
      .order(updated_at: :desc)

    if params[:search].present?
      @plants = @plants.search_by_title_and_description(params[:search])
    end
  end

  def show
    @plant = Plant.find(params[:id])
    @plant_interest = PlantInterest.find_or_initialize_by(plant: @plant, user: current_user)
    @users_other_plants = policy_scope(@plant.user.plants).where.not(id: @plant.id).includes(:user)
    @chat = Chat.find_by(user: current_user, other_user: @plant.user)
    authorize(@plant)
  end

  def new
    @plant = Plant.new
    authorize(@plant)
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user = current_user
    if @plant.save
      redirect_to plant_path(@plant)
    else
      render :new
    end
  end

  def edit
    @plant = Plant.find(params[:id])
    authorize(@plant)
  end

  def update
    @plant = Plant.find(params[:id])
    authorize(@plant)

    @plant.assign_attributes(plant_params.except(:pictures))

    if @plant.valid?
      # TODO: picture specific CRUD
      if params[:plant][:pictures].present?
        @plant.pictures.purge
        @plant.pictures.attach(params[:plant][:pictures])
      end

      @plant.save
      redirect_to plant_path(@plant)
    else
      render :edit
    end
  end

  def destroy
    plant = Plant.find(params[:id])
    authorize plant

    plant.destroy
  end

  private

  def plant_params
    params.require(:plant).permit(:title, :description, :price, :cover_photo, pictures: [], category_ids: [])
  end
end

app/views/plants/_card.html.erb
<div class="plant-card">
  <%= link_to plant_path(plant) do %>
  
    <div
      class="plant-card__cover-photo"
      data-reflex-permanent
      data-target="plant-cards.card"
      data-background-image-url="<%= cl_image_path plant.cover_photo.key, width: 320 * 2, height: 180 * 2, crop: :fill %>"
    ></div>
  <% end %>

  <div class="plant-card__avatar" style="background-image: url('<%= cl_image_path plant.user.profile_picture.key %>');"></div>

  <% favourite = plant.favourites.to_a.find { |fav| fav.user == current_user} %>

  <% if user_signed_in? %>
    <% if favourite %>
      <% if policy(favourite).destroy? %>
        <%= image_tag "heart_pink--filled.svg", class: "plant-card__heart", width: 24, height: 24, data: {
          reflex: "click->FavouritesReflex#destroy",
          favourite_id: favourite.id
        } %>
      <% end %>
    <% else %>
      <% favourite = plant.favourites.new(user: current_user) %>
      <% if policy(favourite).create? && plant.user != current_user %>
        <%= image_tag "heart_pink.svg", class: "plant-card__heart", width: 24, height: 24, data: {
          reflex: "click->FavouritesReflex#create",
          plant_id: plant.id
        } %>
      <% end %>
    <% end %>
  <% end %>

  <div class="plant-card__body">
    <%= link_to plant_path(plant), class: "text-decoration-none" do %>
      <h2 class="plant-card__title font-text font-colour-charcoal font-weight-regular font-size-18"><%= plant.title %></h2>
    <% end %>

    <div class="plant-card__lower">
      <p class="plant-card__date font-text font-colour-light-grey font-size-12">Montreal | <%= plant.created_at.strftime("%b %e, %Y") %></p>

      <% if plant.price_cents == 0 %>
        <p class="plant-card__price font-text font-colour-charcoal font-weight-medium font-size-18">FREE</p>
      <% else %>
        <p class="plant-card__price font-text font-colour-charcoal font-weight-medium font-size-18"><%= number_to_currency plant.price_cents / 100 %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/plants/_plant.html.erb
<div class="plant-card">
  <%= link_to plant_path(plant) do %>
  
    <div class="plant-card__cover-photo" style="background-image: url('<%= cl_image_path plant.cover_photo.key %>');" data-target="plant-cards.card" data-background-image-url="<%= cl_image_path plant.cover_photo.key %>"></div>
  <% end %>

  <div class="plant-card__avatar" style="background-image: url('<%= cl_image_path plant.user.profile_picture.key %>');"></div>

  <% favourite = plant.favourites.to_a.find { |fav| fav.user == current_user} %>

  <% if user_signed_in? %>
    <% if favourite %>
      <% if policy(favourite).destroy? %>
        <%= image_tag "heart_pink--filled.svg", class: "plant-card__heart", width: 24, height: 24, data: {
          reflex: "click->FavouritesReflex#destroy",
          favourite_id: favourite.id
        } %>
      <% end %>
    <% else %>
      <% favourite = plant.favourites.new(user: current_user) %>
      <% if policy(favourite).create? && plant.user != current_user %>
        <%= image_tag "heart_pink.svg", class: "plant-card__heart", width: 24, height: 24, data: {
          reflex: "click->FavouritesReflex#create",
          plant_id: plant.id
        } %>
      <% end %>
    <% end %>
  <% end %>

  <div class="plant-card__body">
    <%= link_to plant_path(plant), class: "text-decoration-none" do %>
      <h2 class="plant-card__title font-text font-colour-charcoal font-weight-regular font-size-18"><%= plant.title %></h2>
    <% end %>

    <div class="plant-card__lower">
      <p class="plant-card__date font-text font-colour-light-grey font-size-12">Montreal | <%= plant.created_at.strftime("%b %e, %Y") %></p>

      <% if plant.price_cents == 0 %>
        <p class="plant-card__price font-text font-colour-charcoal font-weight-medium font-size-18">FREE</p>
      <% else %>
        <p class="plant-card__price font-text font-colour-charcoal font-weight-medium font-size-18"><%= number_to_currency plant.price_cents / 100 %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/plants/edit.html.erb
<div class="plants-form">
  <div class="plants-form__header">
    <h1 class="plants-form__title font-title font-size-24 font-colour-charcoal">Edit "<%= @plant.title %>"</h1>
    <p class="font-text font-size-14 font-colour-light-grey">Once your edit is approved by PlantBnb moderators it will be publically visible</p>
  </div>

  <%= simple_form_for(@plant) do |f| %>
    <%= f.input :title, input_html: { autocomplete: "off", placeholder: "" } %>
    <%= f.input :description, hint: "Maximum of 30 characters" %>
    <%= f.input :price, hint: "Leave blank if your plant is free", input_html: { autocomplete: "off", value: nil } %>
    <%= f.input :cover_photo, required: true %>
    <%= f.input :pictures, hint: "Maximum of 3 pictures", input_html: { multiple: true } %>
    <%= f.association :categories, input_html: { class: "select2" } %>

    <div>
      <%= f.submit "Submit for Approval"%>
    </div>
  <% end %>
</div>

app/views/plants/index.html.erb
<% if params[:search] %>
  <h1 class="plants-index__title font-title font-colour-black font-weight-medium font-size-30"><%= pluralize(@plants.count, "result") %> for "<%= params[:search] %>"</h1>
<% end %>

<div data-controller="plant-cards">
  <div class="plants-index-card-container" data-target="plant-cards.container">
      <% @plants.each do |plant| %>
      <%= render "plants/card", plant: plant %>
    <% end %>
    <div style="width: 320px;"></div>
  </div>
</div>

app/views/plants/new.html.erb
<div class="plants-form">
  <div class="plants-form__header">
    <h1 class="plants-form__title font-title font-size-24 font-colour-charcoal">Post your plant</h1>
    <p class="font-text font-size-14 font-colour-light-grey">Once your post is approved by PlantBnb moderators it will be publically visible </p>
  </div>

  <%= simple_form_for(@plant) do |f| %>
    <%= f.input :title, input_html: { autocomplete: "off", placeholder: "" } %>
    <%= f.input :description, hint: "Maximum of 30 characters" %>
    <%= f.input :price, hint: "Leave blank if your plant is free", input_html: { autocomplete: "off", value: nil } %>
    <%= f.input :cover_photo, required: true %>
    <%= f.input :pictures, hint: "Maximum of 4 pictures", input_html: { multiple: true } %>
    <%= f.association :categories, input_html: { class: "select2" } %>

    <div>
      <%= f.submit "Post your plant" %>
    </div>
  <% end %>
</div>

app/views/plants/show.html.erb
<div class="plants-show__container">
  <div class="plants-show__left-column">
    <div class="plants-show__top-left">
      <div>
        <h1 class="plants-show__title font-title font-weight-medium font-size-20 font-colour-charcoal"><%= @plant.title %></h1>

        <% if @plant.price_cents == 0 %>
          <p class="font-text font-weight-medium font-size-20 font-colour-charcoal">FREE</p>
        <% else %>
          <p class="font-text font-weight-medium font-size-20 font-colour-charcoal"><%= number_to_currency @plant.price_cents / 100 %></p>
        <% end %>
      </div>

      <div>
        <% favourite = Favourite.find_or_initialize_by(user: current_user, plant: @plant) %>

        <% if favourite.persisted? %>
          <% if policy(favourite).destroy? %>
            <%= image_tag "heart_pink--filled.svg", width: 26, height: 26, data: {
              reflex: "click->FavouritesReflex#destroy",
              favourite_id: favourite.id
            } %>
          <% end %>
        <% else %>
          <% if policy(favourite).create? && @plant.user != current_user %>
            <%= image_tag "heart_pink.svg", width: 26, height: 26, data: {
              reflex: "click->FavouritesReflex#create",
              plant_id: @plant.id
            } %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="plant-picture-gallery" data-controller="plant-pictures-gallery" data-reflex-permanent>
      <div
        class="plant-picture-gallery__main-picture"
        style="background-image: url('<%= cl_image_path @plant.cover_photo.key, height: 380, crop: :scale %>')"
        data-target="plant-pictures-gallery.mainPicture"
      ></div>

      <% if @plant.pictures.any? %>
        <div class="plant-picture-gallery__thumbnails">
          <div
            class="plant-picture-gallery__thumbnail plant-picture-gallery__thumbnail--selected"
            style="background-image: url('<%= cl_image_path @plant.cover_photo.key, height: 380, crop: :scale %>')"
            data-action="click->plant-pictures-gallery#selectPicture"
            data-target="plant-pictures-gallery.thumbnail"
            data-active="true"
            data-image-url="<%= cl_image_path @plant.cover_photo.key %>"
          ></div>
          <% @plant.pictures.each do |picture| %>
            <div
              class="plant-picture-gallery__thumbnail"
              style="background-image: url('<%= cl_image_path picture.key, height: 380, crop: :scale %>')"
              data-action="click->plant-pictures-gallery#selectPicture"
              data-target="plant-pictures-gallery.thumbnail"
              data-image-url="<%= cl_image_path picture.key %>"
            ></div>
          <% end %>
        </div>
      <% end %>
    </div>

    <h3 class="plant-show__description-header font-text font-weight-regular font-colour-grey font-size-18">Description</h3>
    <% @plant.description.split("\n").each do |description_paragraph| %>
      <p class="font-text font-weight-light font-colour-grey font-size-16" style="margin-bottom: 16px;"><%= description_paragraph %></p>
    <% end %>
  </div>

  <div class="plants-show__right-column">
    <p class="plants-show__time-posted-ago font-text font-colour-grey font-size-14">Posted <%= time_ago_in_words(@plant.created_at) %> ago in Montreal</p>
    <p class="font-text font-colour-black font-weight-medium font-size-14">View on map</p>

    <% if @plant_interest.persisted? %>
      <div class="plants-show__contact-form">
        <h2 class="plants-show__form-title font-text font-colour-charcoal font-size-14 font-weight-medium">You've contacted <%= @plant.user.name %> about this plant. Click <%= link_to "here", chat_path(@chat), class: "font-colour-black font-weight-medium text-decoration-underline" %> to chat.</h2>
      </div>
    <% elsif policy(@plant_interest).create? && current_user != @plant.user %>
      <div class="plants-show__contact-form">
        <h2 class="plants-show__form-title font-text font-colour-charcoal font-size-14 font-weight-medium">Contact <%= @plant.user.name %> regarding this plant</h2>
        <%= form_with url: plant_plant_interests_path(@plant) do %>
          <%= text_area_tag "message[content]", "", placeholder: "Write a message...", class: "plants-show__message-content" %>
          <%= submit_tag "Send Message", class: "button-green button-fluid" %>
        <% end %>
      </div>
    <% end %>

    <div class="plants-show__plant-owner">
      <div class="plants-show__plant-owner-picture" style="background-image: url('<%= cl_image_path @plant.user.profile_picture.key %>')"></div>
      <div>
        <p class="font-text font-colour-grey font-weight-regular font-size-14"><%= @plant.user.name %></p>
        <div class="plant-show__plant-owner-rating">
          <% if @plant.user.average_rating %>
            <p>
              <% @plant.user.average_rating.floor.times do %>
                <%= image_tag "star--filled.svg", style: "margin-left: -5px;", width: 20, height: 20 %>
              <% end %>

              <% (5 - @plant.user.average_rating.floor).times do %>
                <%= image_tag "star.svg", style: "margin-left: -5px;", width: 20, height: 20 %>
              <% end %>
            </p>
            <p class="font-text font-colour-grey font-weight-regular font-size-14"><%= @plant.user.average_rating.round(1) %></p>
            <p class="font-text font-colour-light-grey font-weight-regular font-size-14">(<%= @plant.user.number_of_ratings %> reviews)</p>
          <% end %>
        </div>
        <p class="font-text font-colour-black font-weight-medium font-size-14">View all listings</p>
      </div>
    </div>

    <% if @users_other_plants.any? %>
      <div class="plants-show__other-plants">
        <h3 class="plants-show__other-plants-title font-text font-size-18 font-weight-regular font-colour-grey"><%= @plant.user.name %>'s other plants</h3>

        <% @users_other_plants.each do |plant| %>
          <div class="users-other-plant-card">
            <%= link_to plant_path(plant) do %>
              <div class="users-other-plant-card__picture" style="background-image: url('<%= cl_image_path plant.cover_photo.key %>');"></div>
            <% end %>

            <div class="users-other-plant-card__body">
              <%= link_to plant.title, plant_path(plant), class: "text-decoration-none font-text font-weight-regular font-size-18 font-colour-charcoal" %>

              <div class="users-other-plant-card__bottom">
                <p class="font-text font-weight-regular font-size-12 font-colour-light-grey">Montreal | <%= plant.created_at.strftime("%b %e, %Y") %></p>

                <% if plant.price_cents == 0 %>
                  <p class="font-text font-weight-medium font-size-28 font-colour-charcoal">FREE</p>
                <% else %>
                  <p class="font-text font-weight-medium font-size-28 font-colour-charcoal"><%= number_to_currency plant.price_cents / 100 %></p>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>